### ISSUE TITLE
Tag 1.2.0 is not published to maven central

### ISSUE THREAD

**Issue by voinikyt** [vzornic/pg-jsonb#7]
Hello, 

Tag 1.2.0 is not published in maven central. The last published version is 1.1.0.
![image](https://user-images.githubusercontent.com/816984/135625995-40ef8ca4-a5f7-4850-b61c-3400be702b4b.png)

can somebody publish it there?

**Comment by borsch** [comment]
+1

**Comment by vedadzornic** [comment]
I've finally pushed 1.2.0 to maven central. However, I have no intention of any longer supporting this lib as I'm being really busy on other projects.

If you're interested in maintaining it, let me know and I can arrange that for you.
